version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - ECR_REPOSITORY="517212389074.dkr.ecr.us-east-1.amazonaws.com/eletricacontinental-api-images"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t eletricacontinental-api-images:latest .
      - docker tag eletricacontinental-api-images:latest $ECR_REPOSITORY:latest
  post_build:
    commands:
      - docker push $ECR_REPOSITORY:latest